### ISSUE TITLE
Move MeteorologicalBulletinSpecialCharacter to fmi-avi-messageconverter

### ISSUE THREAD

**Issue by petringo** [fmidev/fmi-avi-messageconverter-tac#103]
Move `fi.fmi.avi.converter.tac.lexer.Lexeme.MeteorologicalBulletinSpecialCharacter' to fmi-avi-messageconverter repository. Perhaps as a topl-level class in `fi.fmi.avi.model.bulletin` package. This will be needed in upcoming changes.

**Comment by patrick-alaspaa** [comment]
I would like this task
