### ISSUE TITLE
SigmetWithinRadius and PolygonCoordinatePair produce different coordinates for the same point

### ISSUE THREAD

**Issue by kasarit** [fmidev/fmi-avi-messageconverter-tac#186]
When you create a SIGMET with a point geometry and then add a radius to it (making a circle with a center point), the coordinates change in the serialized TAC. This seems like a bug.

* `SigmetWithinRadius` uses its own logic to create coordinate points for a circle center point.
* `PolygonCoordinatePair` uses `GeometryHelper.getGeoLexemes`

**Comment by ernstdevreede** [comment]
Yep, good catch!
The SigmetWithinRadius element incorreclty shows the coordinates with decimal_part , whereas it should show (decimal_part*60).
