### ISSUE TITLE
Failing tests in SWXTACParserTest

### ISSUE THREAD

**Issue by kasarit** [fmidev/fmi-avi-messageconverter-tac#35]
Test failures in [src/test/java/fi/fmi/avi/converter/tac/swx/SWXTACParserTest.java](../blob/master/src/test/java/fi/fmi/avi/converter/tac/swx/SWXTACParserTest.java)
Currently the assertions in testInvalid* tests only check whether there are any conversion issues. These assertions need to be made more granular and an assertion needs to be added for the conversion status and perhaps for the converted message.

**Comment by patrick-alaspaa** [comment]
Assign this to me
