### ISSUE TITLE
DTGIssueTime should be split into label and content in SWX advisory TAC parsing

### ISSUE THREAD

**Issue by kasarit** [fmidev/fmi-avi-messageconverter-tac#38]
The label and content of SWX advisory issue time (`DTG:              20200928/2319Z`) are parsed together as DTGIssueTime. The label should be parsed separately into a SWX_ISSUE_TIME_LABEL lexeme "DTG:". The issue time should also be a lexeme of its own.

**Comment by patrick-alaspaa** [comment]
Assign this to me
