### ISSUE TITLE
Reject end token (=) within any other lexeme

### ISSUE THREAD

**Issue by petringo** [fmidev/fmi-avi-messageconverter-tac#58]
The TAC message end token `=` cannot occur anywhere within a TAC message. Therefore it should be never accepted within any other lexeme than the end token lexeme.

Currently following is accepted within an SWX Advisory and parsed (otherwise correctly) without errors:

```
OBS SWX:          01/2202Z= NO SWX EXP
```

```
OBS SWX:          01/2202Z NO SWX EXP=
```

```
OBS SWX:          01/2202Z NO SWX EXP
=
FCST SWX +6 HR:   02/0500Z NO SWX EXP
```

```
OBS SWX:          01/2202Z NO SWX EXP
== ===
FCST SWX +6 HR:   02/0500Z NO SWX EXP
```

These is only examples, more faulty cases may exist as well. The end token seems to be accepted between/at end of any label-content pairs.

**Comment by patrick-alaspaa** [comment]
Assign this to me
