### ISSUE TITLE
Fix advisory message coordinate decimals handling

### ISSUE THREAD

**Issue by petringo** [fmidev/fmi-avi-messageconverter-tac#59]
Coordinates in SWX Advisory message must be parsed in following way:
1. Two/three digits: as integer with no decimals
2. Four/five digits: as number with two decimals

Coordinates in SWX Advisory message should be serialized in following way:
1. No decimals (decimal part is zero): as two/three digits with leading zeroes with leading zeroes
2. Has decimals (decimal part is not zero): as four/five digits with leading zeroes, rounded in two decimals

If number of digits mismatch definitions above, an error should be raised, as the interpretation of digits is ambiguous.

Issues found so far in current implementation:
1. Two/three digit number is interpreted as two decimal number.
2. Leading zeroes are omitted upon serialization.

**Comment by patrick-alaspaa** [comment]
Assign this to me

**Comment by petringo** [comment]
The specification of this task was actually wrong, sorry for that. I'll have to make a new one. But #70 fixes the issue with interpretation of decimals during parse, so I'm closing this.
