### ISSUE TITLE
SWXA hemispheres exceeding 180 deg is parsed as negated polygon

### ISSUE THREAD

**Issue by petringo** [fmidev/fmi-avi-messageconverter-tac#69]
For example `HNH E150 - W030` produces polygon

```
90.0, 150.0, 60.0, 150.0, 60.0, -30.0, 90.0, -30.0, 90.0, 150.0
```

Instead of E150 to W030, it should produce a multipolygon from E150 to E180 and W180 to W030.

**Comment by patrick-alaspaa** [comment]
Assign this to me

**Comment by patrick-alaspaa** [comment]
Could I have a few more examples of values that should and shouldn't be multi polygons in order to make sure the processing is correct.

**Comment by petringo** [comment]
As a rule of thumb, the longitude (x axis) value always increases, read from left to right. Thus when going from east to west, the band goes around 180 deg, and a multipolygon up to 180 deg and from -180 deg is needed.

Some fictional examples when passing -180/180 deg / multipolygon needed:
```
W030 - W100
E180 - E090
E060 - W060
```

Some fictional examples when -180/180 deg is not passed / single polygon only:

```
W100 - W030
E090 - E180
W060 - E060
```

**Comment by petringo** [comment]
But there's one exception: -180 and 180 are the same in general. Therefore if either of ends is E180 or W180 despite of order, only single polygon shall be created. Some example cases:

```
W180 - E180
E180 - W180

E000 - W180
W000 - W180
W000 - E180
E000 - E180

W180 - E000
W180 - W000
E180 - W000
E180 - E000
```

**Comment by petringo** [comment]
There's still one special case regarding -180/180 deg. Following cases that circle half way around the world from/to -180 or 180 deg can be expressed in multiple ways.

* -180 - 0 deg
  * `E180 - W000`
  * `E180 - E000`
  * `W180 - E000`
  * `W180 - W000`
* 0 - 180 deg
  * `E000 - W180`
  * `E000 - E180`
  * `W000 - E180`
  * `W000 - W180`

Theoretically some of the alternatives above would produce a multipolygon of two polygons, another of them being empty. Empty polygons can and should be omitted, and simplified to a single polygon.

So no empty polygons should be produced in general. Therefore following examples circle around the whole world.

* -180 - 180 deg
  * `W180 - E180`
  * `E180 - W180`
* -180 - 0 deg, 0 - 180 deg (multipolygon)
  * `E000 - W000`
  * `W000 - E000`
* -180 - _n_ deg, _n_ - 180 deg (multipolygon)
  * any two longitudes being effectively same (_n_)

**Comment by petringo** [comment]
Somehow I tend to expect that polygons in any case should _not_ contain `-0.0`, but only `0.0`. I don't know if negative zero is valid here at all?

**Comment by patrick-alaspaa** [comment]
I removed the -0 values

**Comment by petringo** [comment]
With TAC polygons, It looks that the latitude axis is not affected by these special cases, as we're not travelling around the world along it, but only from north to south or vice versa. Please correct me if I'm wrong.
