### ISSUE TITLE
Create overview documentation for developers

### ISSUE THREAD

**Issue by petringo** [fmidev/fmi-avi-messageconverter-tac#95]
Write an overview of the technical architecture and conversion workflow for new developers getting familiar with the code.

Describe
1. basic concepts, design decisions and principles, conventions
2. basic workflow of conversion: parsing and serialization, involved classes and their roles
3. howto: adding support for a new message type

Prefer
* high level over details
* brief description over verbose
* lists and diagrams over written sentences and paragraphs

Target audience is a developer of this library getting familiar with it.

Write the document as [GitHub Flavored Markdown](https://github.github.com/gfm/) file under `docs` directory at root of the project tree.

**Comment by petringo** [comment]
Model-related documentation can be written in fmidev/fmi-avi-messageconverter#76 and referenced here.

**Comment by patrick-alaspaa** [comment]
Assign tisto me please
